const POST_STATUS_MAP = {
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  BLOCK: 'block',
  TRASH: 'trash',
};
const POST_STATUSES = Object.values(POST_STATUS_MAP);
const POST_CURRENCIES = ['USD', 'EUR', 'UAH'];
const POST_TYPE_MAP = {
  LAND_RENT: 'rent',
  LAND_SALE: 'sale',
};
const POST_TYPES = Object.values(POST_TYPE_MAP);
const POST_PURPOSE_MAP = {
  AGRICULTURAL_LAND: 0,
  LAND_FOR_HOUSING_AND_PUBLIC_BUILDINGS: 1,
  WELLNESS_LAND: 2,
  LAND_FOR_RECREATIONAL_PURPOSES: 3,
  FORESTRY_LANDS: 4,
  WATER_FUND_LAND: 5,
  LAND_FOR_INDUSTRY_TRANSPORT_AND_OTHER_PURPOSES: 6,
  LAND_STOCK_RESERVE_FUND_AND_COMMON_USE: 7,
};
const POST_PURPOSES = Object.values(POST_PURPOSE_MAP);

module.exports = {
  POST_STATUS_MAP,
  POST_STATUSES,
  POST_CURRENCIES,
  POST_TYPE_MAP,
  POST_TYPES,
  POST_PURPOSE_MAP,
  POST_PURPOSES,
};
